name: Testing cmake with c++
on:
 push:
  branches:
  - dev
  - uat
  - prod
  - master

env:
 VERSION: "1.0"

jobs:
  cmake-cplusplus-app:
    name: cmake-cplusplus-app
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Create Folder and build it
      run: |
       mkdir -p build && cd build && cmake && make